<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Raj" failures="2" tests="6" name="Test(failed)(failed)" time="0.085" errors="0" timestamp="2023-02-17T12:01:36 IST">
  <testcase classname="TestNGInterview.RerunFailedtestcase1" name="equal1" time="0.013">
    <skipped/>
  </testcase> <!-- equal1 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase1" name="equal1" time="0.001">
    <skipped/>
  </testcase> <!-- equal1 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase1" name="equal1" time="0.002">
    <skipped/>
  </testcase> <!-- equal1 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase1" name="equal1" time="0.002">
    <skipped/>
  </testcase> <!-- equal1 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase1" name="equal1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [10] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [5]
at TestNGInterview.RerunFailedtestcase1.equal1(RerunFailedtestcase1.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- equal1 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase1" name="equal3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [10] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [5]
at TestNGInterview.RerunFailedtestcase1.equal3(RerunFailedtestcase1.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- equal3 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase1" name="equal2" time="0.0">
    <ignored/>
  </testcase> <!-- equal2 -->
</testsuite> <!-- Test(failed)(failed) -->
